#!/usr/bin/env bash

paru -S --needed \
uwsm \
hyprshot \
hyprutils \
hyprpicker \
hyprlang \
hypridle \
hyprland-qt-support \
hyprland-qtutils \
hyprcursor \
hyprwayland-scanner \
hyprland \
hyprlock \
hypridle \
hyprpolkitagent \
hypridle \
hyprutils \
hyprpicker \
xdg-desktop-portal-hyprland \
xdg-desktop-portal \
xdg-desktop-portal-gtk \
pavucontrol \
wireplumber \
gnome-keyring \
libdbusmenu-gtk3 \
gtk4 \
libportal-gtk4 \
libsoup3 \
fontconfig \
ttf-jetbrains-mono-nerd \
ttf-firacode-nerd \
ttf-nerd-fonts-symbols-mono \
ttf-rubik-vf \
bibata-cursor-theme-bin \
papirus-icon-theme \
libadwaita \
breeze-plus \
adw-gtk-theme \
kvantum \
qt6ct \
qt5ct \
playerctl \
brightnessctl \
ddcutil \
wl-clipboard \
cliphist \
stow \
rofi-wayland \
zoxide \
starship \
yazi \
dolphin \
nvim \
fnm-bin \
pnpm \
swww \
kitty \
matugen-bin \
eza \
better-control-git \
nm-connection-editor \
zen-brwoser-bin \
visual-studio-code-bin \
aylurs-gtk-shell \
